<ul class="mainNav">
<?php
$urls = array();
$urls[] = array(
    'label' => 'Lucene - search',
    'url' => $this->url(array(
        'controller' => 'lucene',
        'action' => 'index'
    ))
);
$urls[] = array(
    'label' => 'Lucene - build',
    'url' => $this->url(array(
        'controller' => 'lucene',
        'action' => 'build'
    ))
);

// capture nav to mainNav placeholder, for footer reuse
$this->placeholder('mainNav')->captureStart();
echo $this->partialLoop('partialLoopNavItem.phtml', $urls);
$this->placeholder('mainNav')->captureEnd();

echo $this->placeholder('mainNav');
?>
</ul>
<hr>